routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','QuestionsController@index');

Route::resource('questions', 'QuestionsController')->except('show');
Route::get('questions/{slug}', 'QuestionsController@show')->name('questions.show');
Route::resource('questions.answers', 'AnswersController')->except('create','show');
Auth::routes();
Route::post('/answers/{answer}/accept','AcceptAnswerController')->name('answer.accept');
Route::get('/home', 'HomeController@index')->name('home');
Route::post('/questions/{question}/favorites','FavoritesController@store')->name('question.favorite');
Route::delete('/questions/{question}/favorites','FavoritesController@destroy')->name('question.unfavorite');
Route::post('/questions/{question}/vote','VoteQuestionController')->name('question.vote');
Route::delete('/questions/{question}/vote','VoteQuestionController')->name('question.vote');
Route::post('/answers/{answer}/vote','VoteAnswerController')->name('answer.vote');
Route::delete('/answers/{answer}/vote','VoteAnswerController')->name('answer.vote');

app/Answer.php
<?php
/** Answer
 * The answers class
 */
namespace App;
use App\Question;
use App\User;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Support\Facades\Event;
use Illuminate\Database\Eloquent\Model;
/** Answer
 * The answers class
 */
class Answer extends Model
{
    use HasFactory;

    use VotableTrait;
    protected $fillable = ['user_id', 'body'];
    protected $appends = ['created_date','body_html','is_best'];

    /** BelongsTO
    * Relationship with question model
    */
    public function question()
    {
        return $this->belongsTo(Question::class);
    }
    /** BelongsTO
    * Relationship with user model
    */
    public function user()
    {
        return $this->belongsTo(User::class);
    }
    /**
     *
     *  This can convert body stored in db to HTML format
     *
     */
    public function getBodyHtmlAttribute()
    {
        return \Parsedown::instance()
            ->setBreaksEnabled(true)
            ->text($this->body, 'breaks_enabled');
    }
    /**
     * The answer will increment the vale ofanswer_count
     * in every call of the this class
     * that's when an answer is created
     */
    public static function boot()
    {
        parent::boot();
        static::created(function ($answer)
        {
            $id = $answer->question_id;
            \App\Question::findOrFail($id)->increment("answers_count");
        });
        static::deleted(function ($answer)
        {
            // question->decrement('answers_count');
            Question::findOrFail($answer->question_id)->decrement("answers_count");
            $question = Question::findOrFail($answer->question_id);
            if ($question->best_answer_id == $answer->id) {
                $question->best_answer_id = 0;
                $question->save();
            }
        });
    }
    public function isBest()
    {
        return $this->id == $this->question->best_answer_id;
    }
    public function getStatusAttribute($answer)
    {
        return $this->isBest() ? 'vote-accept' : '';
    }
    public function getIsBestAttribute($answer)
    {
        return $this->isBest();
    }
    public function getCreatedDateAttribute()
    {
        return $this->created_at->diffforhumans();
    }

}

app/Http/Controllers/AnswersController.php
<?php

namespace App\Http\Controllers;

use App\Answer;
use App\Question;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;


class AnswersController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth',['except'=>['index']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Question $question)
    {
        return $question->answers()->with('user')->simplePaginate(3);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Question $question, Request $request)
    {

        $answer = $question->answers()->create($request->validate([
            'body' => 'required'
            ])+ ['user_id' => Auth::id()]);
        if (request()->expectsJson()) {
            # code...
            $data = [   'message' => 'Your answer has been submitted',
                        'answer' => $answer->load('user')   ];
            return response()->json($data);
        }
        return back()->with('success',"Your answer has been submitted");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function show(Answer $answer)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question, Answer $answer)
    {
        $this->authorize('update' , $answer);
        return view('answers.edit' , compact('question' , 'answer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request , Question $question , Answer $answer)
    {
        $this->authorize('update' , $answer);

        $answer->update( $request
        ->validate( ['body' => 'required', ] ) );
        if ($request->expectsJson()) {
            # code...
            $data = [ 'message' => 'Your answer has been updated', 'body_html' => $answer->body_html ];
            return response()->json($data);
        }
        return redirect()->route('questions.show',$question->slug)->with('success','Your answer has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request , Question $question , Answer $answer)
    {
        $this->authorize('delete', $answer);
        $answer->delete();
        if ($request->expectsJson()) {
            # code...
            $data = [ 'message' => 'Your answer has been removed'];
            return response()->json($data);
        }
        return back()->with('success', 'Answer removed ');

    }
}

resources/views/answers/_answer.blade.php
<answer :model='{{ $answer }}' inline-template>
    <div class="media post">
        <vote :model='{{ $answer }}' name='answer'></vote>

        <div class="media-body">
            <form v-if="editing" @submit.prevent="answerupdate" >
                <div class="form-group">
                  <textarea required v-model="body" class="form-control {{ $errors->has('body') ? 'is-invalid' : ''}}" placeholder="Explaine" name="" id="" rows="10"></textarea>
                </div>
                <button type="submit" :disabled="isInvalid"  class="btn btn-outline-primary">Edit</button>
                <button type="button" @click="answercancel"  class="btn btn-outline-secondary">Cancel</button>
            </form>
            <div v-if="!editing">

                    <div v-html="bodyHtml"></div>

                    <div class="row">
                        <div class="col-4">
                            <div class="ml-auto"><!-- href="{{ route('questions.answers.edit',[$question->id,$answer->id]) }}" -->
                                @can('update',$answer)
                                    <a @click.prevend="answeredit"  data-loading-text=”Deleting…”  class="btn btn-sm btn-outline-info" >Edit</a>
                                @endcan
                                @can('delete',$answer)
                                        <button @click.prevend="answerdelete" data-loading-text=”Deleting…”  class="btn btn-sm btn-outline-danger" >Delete</button>
                                @endcan
                            </div>
                        </div>
                        <div class="col-4"></div>
                        <div class="col-4">
                            <user-info :model='{{ $answer }}' label='Answered  '></user-info>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</answer>

resources/views/answers/_create.blade.php
@auth
    <div class="col-md-12">
        <div class="card mt-4">
            <div class="card-body">
                <div class="card-titlr">
                    <div class="d-flex">
                    <h3>Your answer</h3>
                    </div>
                </div><hr>
                <form action="{{ route('questions.answers.store',$question->id)}}" method="post">
                    @csrf
                    <div class="form-group">

                        <textarea name="body" id="question-body" rows="10" class="form-control {{ $errors->has('body') ? 'is-invalid' : ''}}" placeholder="Explaine"></textarea>
                        @if ($errors->has('body'))
                      <div class="invalid-feedback">
                          <strong>{{ $errors->first('body')}}</strong>
                      </div>
                  @endif
                    </div>
                    <div class="form-group">
                      <input type="submit" name="" id="" class="btn btn-lg btn-outline-primary" title="Submite" placeholder="" aria-describedby="helpId">
                    </div>
                </form>
            </div>
        </div>
    </div>
@endauth
@guest
    <div class="col-md-12">
        <div class="card mt-4">
            <div class="card-body">
                <div class="card-titlr">
                    <div class="d-flex">
                        <h3>Your answer</h3>
                    </div>
                </div>
                <hr>
                <a href="{{ route('login')}}">Login to post an answer</a>
            </div>
        </div>
    </div>
@endguest

resources/views/answers/_index.blade.php
@if ($answersCount > 0)
    <div class="col-md-12" v-cloak>
        <div class="card mt-4">

            <div class="card-body">
                <div class="card-titlr">
                    <div class="d-flex">
                        <h3 class="info">{{$answersCount . ' ' . Str::plural('Answer',$answersCount ) }}</h3>
                    </div>
                </div>
                <hr>
                @include('layouts._messages')
                @forelse($answers as $answer)
                @include('answers._answer',['answer' => $answer])
                @empty
                    <div class="alert alert-danger">
                        <strong>Sorry!</strong> there is no answer yet
                    </div>
                @endforelse
            </div>
        </div>
    </div>
@endif

resources/views/answers/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
<div class="row mt-3">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">

            <div class="card-titlr">
                <h2>Editing answer for question : <strong>{{ $question->title}}</strong></h2>

            </div>
                @auth
                    <hr>
                    <form action="{{ route('questions.answers.update',[$question->id, $answer->id])}}" method="post">
                        @csrf
                        @method('PATCH')
                        <div class="form-group">

                            <textarea name="body" id="question-body" rows="10" class="form-control {{ $errors->has('body') ? 'is-invalid' : ''}}" placeholder="Explaine">{{ old('body',$answer->body)}}</textarea>
                            @if ($errors->has('body'))
                        <div class="invalid-feedback">
                            <strong>{{ $errors->first('body')}}</strong>
                        </div>
                    @endif
                        </div>
                        <div class="form-group">
                        <input type="submit" name="" id="" class="btn btn-lg btn-outline-primary" title="Update" placeholder="" aria-describedby="helpId">
                        </div>
                    </form>
                @endauth
            </div>
        </div>
    </div>
</div>
</div>
</div>
@endsection