routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','QuestionsController@index');

Route::resource('questions', 'QuestionsController')->except('show');
Route::get('questions/{slug}', 'QuestionsController@show')->name('questions.show');
Route::resource('questions.answers', 'AnswersController')->except('create','show');
Auth::routes();
Route::post('/answers/{answer}/accept','AcceptAnswerController')->name('answer.accept');
Route::get('/home', 'HomeController@index')->name('home');
Route::post('/questions/{question}/favorites','FavoritesController@store')->name('question.favorite');
Route::delete('/questions/{question}/favorites','FavoritesController@destroy')->name('question.unfavorite');
Route::post('/questions/{question}/vote','VoteQuestionController')->name('question.vote');
Route::delete('/questions/{question}/vote','VoteQuestionController')->name('question.vote');
Route::post('/answers/{answer}/vote','VoteAnswerController')->name('answer.vote');
Route::delete('/answers/{answer}/vote','VoteAnswerController')->name('answer.vote');

app/Question.php
<?php
/** Question
 * The questions class
 */
namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Routing\Route;
use Illuminate\Support\Str;
use App\Answer;
use App\Http\Controllers\AcceptAnswerController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Question extends Model
{
    use HasFactory;

    use VotableTrait;
    protected $fillable = ['title', 'body'];
    protected $appends = ['body_html','created_date','favorites_count','is_favorited'];
    public function user()
    {
        return $this->belongsTo(User::class);
    }
    public function setTitleAttribute($title)
    {
        $this->attributes['title'] = $title;
        $this->attributes['slug'] = str::slug($title);
    }
    public function getUrlAttribute()
    {
        return Route('questions.show', $this->slug);
    }
/*    public function getVotesCountAttribute()
    {
        return $this->votes_count;
    }*/
    public function getCreatedDateAttribute()
    {
        return $this->created_at->diffforhumans();
    }
    public function getStatusAttribute()
    {
        if ($this->answers_count > 0) {
            if ($this->best_answer_id) {
                return 'answered-accepted';
            }
            return 'answered';
        }
        return 'unaswered';
    }

    /**
     *
     *  This can convert body stored in db to HTML format
     *
     */
    public function getBodyHtmlAttribute()
    {
        //return clean($this->bodyHtml());
        return $this->bodyHtml();
    }
    /**
     * Answer relationship
     */
    public function answers()
    {
        return $this->hasMany(Answer::class)->orderBy('votes_count','DESC') ;
    }
    public function acceptBestAnswer($answer)
    {
        $this->best_answer_id=$answer->id;
        $this->save();
    }
    public function favorites()
    {
        return $this->belongsToMany(User::class,'favorites')->withTimestamps();
    }
    public function isFavorited()
    {
        return $this->favorites()->where('user_id', auth()->id())->count() > 0;
    }
    public function getIsFavoritedAttribute()
    {
        return $this->isFavorited();
    }
    public function getFavoritesCountAttribute()
    {
        return $this->favorites->count();
    }
    public function getExcerptAttribute()
    {
        return $this->excerpt(254);
    }
    public function excerpt($var)
    {
        return Str::limit(strip_tags($this->bodyHtml()),$var );
        # code...
    }
    protected function bodyHtml()
    {
        return \Parsedown::instance()
            ->setBreaksEnabled(true)
            ->text($this->body, 'breaks_enabled');
    }
}

app/Http/Controllers/QuestionsController.php
<?php

namespace App\Http\Controllers;

use App\Question;
use Illuminate\Http\Request;
use App\Http\Requests\AskQuestionRequest;
use Laravel\Ui\Presets\Vue;

class QuestionsController extends Controller
{
    /**
     * Constructeur de la class QuestionsController
     * Appel du Middlewhere d'authentification
     */
    public function __construct()
    {
        $this->middleware('auth',['except'=>['index','show']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // \DB::enableQueryLog();
        $questions = Question::latest()->simplepaginate(5);
        // view('questions.index',compact('questions'))->render();
        // dd(\DB::getQueryLog());
        return view('questions.index',compact('questions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $question = new Question();
        return view('questions.create',compact('question'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AskQuestionRequest $request)
    {
        $request->user()->questions()->create($request->only('title','body'));
        return redirect()->route('questions.index')->with('success','Your question has been submited');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function show(Question $question)
    {
        $question->increment('views');
        return view('questions.show',compact('question'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question)
    {
        if (\Gate::denies('update-question',$question)) {
            # code...
            abort(403,'Access denied');
        }
        return view('questions.edit', compact('question'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function update(AskQuestionRequest $request, Question $question)
    {
        if (\Gate::denies('update-question',$question)) {
            # code...
            abort(403,'Access denied');
        }
        $this->authorize('update',$question);
        $question->update($request->only('title','body'));
        if ($request->expectsJson()) {
            # code...
            $data = [ 'message' => 'Your question has been updated',
            'body_html' => $question->body_html ];
            return response()->json($data);
        }
        return redirect()->route('questions.index')->with('success','Your question has been updated');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question)
    {
        if (\Gate::denies('delete-question',$question)) {
            # code...
            abort(403,'Access denied');
        }
        $this->authorize('delete',$question);
        $question->delete();
        if (request()->expectsJson()) {
            # code...
            $data = [ 'message' => 'Your question has been removed'];
            return response()->json($data);
        }
        return redirect()->route('questions.index')->with('success','Your question has been deleted');

    }
}

resources/views/questions/_excerpt.blade.php
<div class="media post">
    <div class="d-flex flex-column counters">
        <div class="vote">
            <strong>{{$question->votes_count }}</strong>{{ Str::plural('Vote',$question->votes_count ) }}
        </div>
        <div class="status {{$question->status }}">
            <strong>{{$question->answers_count }}</strong>{{ Str::plural('Answer',$question->answers_count ) }}
        </div>
        <div class="view">
            {{$question->views . ' ' . Str::plural('View',$question->views ) }}
        </div>
    </div>
    <div class="media-body">
        <div class="d-flex align-item-center">
            <h3 class="mt-0"><a href="{{$question->url }}">{{$question->title }}</a></h3>
            <div class="ml-auto">
                @auth
                    <ul class="list-inline">
                    <li class="list-inline-item">
                            @if (Auth::user()->can('update-question',$question))
                                <a onclick="return confirm('R u sure')" data-loading-text=”Deleting…”  class="btn btn-sm btn-outline-info" href="{{ route('questions.edit',$question->id) }}">Edit</a>
                            @endif
                    </li>
                    <li class="list-inline-item">
                            @if (Auth::user()->can('delete-question',$question))
                                <form class="form-delete" action="{{ route('questions.destroy',$question->id) }}" method="post">
                                    @method('DELETE')
                                    @csrf
                                    <button onclick="return confirm('R u sure')" data-loading-text=”Deleting…” id="myInput" type="submit" class="btn btn-sm btn-outline-danger" >Delete</button>
                                </form>
                            @endif
                    </li>
                </ul>
                @endauth
            </div>
        </div>
        <p class="lead">
            Asked by :
            <a href="{{$question->user->url }}">{{$question->user->name }}</a>
            <small class="text-muted">{{$question->created_date }}</small>
            </p>
        <div class="excerpt">{{$question->excerpt }}</div>
    </div>
</div>

resources/views/questions/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex align-item-center">
                        <h2>Ask questions</h2>
                        <div class="ml-auto" >
                            <a href="{{ route('questions.index')}}" class="btn btn-outline-secondary">Show all questions</a>
                            </div>
                    </div>

                </div>

                <div class="card-body">


                    <div >

                        <form action="{{ route('questions.store')}}" method="POST">
                            @include('layouts._form', ['btntxt'=> 'Ask this new question'])
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/questions/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container col-md-12">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex align-item-center">
                        <h2>Edit questions</h2>
                        <div class="ml-auto" >
                            <a href="{{ route('questions.index')}}" class="btn btn-outline-secondary">Show all questions</a>
                            </div>
                    </div>

                </div>

                <div class="card-body">


                    <div >

                        <form action="{{ route('questions.update', $question->id)}}" method="POST">
                            {{ method_field('PUT') }}
                            @include('layouts._form', ['btntxt'=> 'Edit this question'])

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/questions/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex align-item-center">
                        <h2>All questions</h2>
                        <div class="ml-auto" >
                            <a href="{{ route('questions.create')}}" class="btn btn-outline-secondary">Ask new question</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    @include('layouts._messages')
                    @forelse ($questions as $question)
                    @include('questions._excerpt')
                    @empty
                        <div class="alert alert-danger">
                            Sorry! <strong>there is no question yet</strong>
                        </div>
                    @endforelse
                </div>
                {{$questions->links() }}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/questions/show.blade.php
    @extends('layouts.app')
    @section('content')
    <div class="container">
        <div class="row justify-content-center">
            <question :model='{{ $question }}'></question>
            <answers :model='{{ $question }}'></answers>
        </div>
    </div>
    @endsection