routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','QuestionsController@index');

Route::resource('questions', 'QuestionsController')->except('show');
Route::get('questions/{slug}', 'QuestionsController@show')->name('questions.show');
Route::resource('questions.answers', 'AnswersController')->except('create','show');
Auth::routes();
Route::post('/answers/{answer}/accept','AcceptAnswerController')->name('answer.accept');
Route::get('/home', 'HomeController@index')->name('home');
Route::post('/questions/{question}/favorites','FavoritesController@store')->name('question.favorite');
Route::delete('/questions/{question}/favorites','FavoritesController@destroy')->name('question.unfavorite');
Route::post('/questions/{question}/vote','VoteQuestionController')->name('question.vote');
Route::delete('/questions/{question}/vote','VoteQuestionController')->name('question.vote');
Route::post('/answers/{answer}/vote','VoteAnswerController')->name('answer.vote');
Route::delete('/answers/{answer}/vote','VoteAnswerController')->name('answer.vote');

app/Answer.php
<?php
/** Answer
 * The answers class
 */
namespace App;
use App\Question;
use App\User;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Support\Facades\Event;
use Illuminate\Database\Eloquent\Model;
/** Answer
 * The answers class
 */
class Answer extends Model
{
    use HasFactory;

    use VotableTrait;
    protected $fillable = ['user_id', 'body'];
    protected $appends = ['created_date','body_html','is_best'];

    /** BelongsTO
    * Relationship with question model
    */
    public function question()
    {
        return $this->belongsTo(Question::class);
    }
    /** BelongsTO
    * Relationship with user model
    */
    public function user()
    {
        return $this->belongsTo(User::class);
    }
    /**
     *
     *  This can convert body stored in db to HTML format
     *
     */
    public function getBodyHtmlAttribute()
    {
        return \Parsedown::instance()
            ->setBreaksEnabled(true)
            ->text($this->body, 'breaks_enabled');
    }
    /**
     * The answer will increment the vale ofanswer_count
     * in every call of the this class
     * that's when an answer is created
     */
    public static function boot()
    {
        parent::boot();
        static::created(function ($answer)
        {
            $id = $answer->question_id;
            \App\Question::findOrFail($id)->increment("answers_count");
        });
        static::deleted(function ($answer)
        {
            // question->decrement('answers_count');
            Question::findOrFail($answer->question_id)->decrement("answers_count");
            $question = Question::findOrFail($answer->question_id);
            if ($question->best_answer_id == $answer->id) {
                $question->best_answer_id = 0;
                $question->save();
            }
        });
    }
    public function isBest()
    {
        return $this->id == $this->question->best_answer_id;
    }
    public function getStatusAttribute($answer)
    {
        return $this->isBest() ? 'vote-accept' : '';
    }
    public function getIsBestAttribute($answer)
    {
        return $this->isBest();
    }
    public function getCreatedDateAttribute()
    {
        return $this->created_at->diffforhumans();
    }

}

app/Question.php
<?php
/** Question
 * The questions class
 */
namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Routing\Route;
use Illuminate\Support\Str;
use App\Answer;
use App\Http\Controllers\AcceptAnswerController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Question extends Model
{
    use HasFactory;

    use VotableTrait;
    protected $fillable = ['title', 'body'];
    protected $appends = ['body_html','created_date','favorites_count','is_favorited'];
    public function user()
    {
        return $this->belongsTo(User::class);
    }
    public function setTitleAttribute($title)
    {
        $this->attributes['title'] = $title;
        $this->attributes['slug'] = str::slug($title);
    }
    public function getUrlAttribute()
    {
        return Route('questions.show', $this->slug);
    }
/*    public function getVotesCountAttribute()
    {
        return $this->votes_count;
    }*/
    public function getCreatedDateAttribute()
    {
        return $this->created_at->diffforhumans();
    }
    public function getStatusAttribute()
    {
        if ($this->answers_count > 0) {
            if ($this->best_answer_id) {
                return 'answered-accepted';
            }
            return 'answered';
        }
        return 'unaswered';
    }

    /**
     *
     *  This can convert body stored in db to HTML format
     *
     */
    public function getBodyHtmlAttribute()
    {
        //return clean($this->bodyHtml());
        return $this->bodyHtml();
    }
    /**
     * Answer relationship
     */
    public function answers()
    {
        return $this->hasMany(Answer::class)->orderBy('votes_count','DESC') ;
    }
    public function acceptBestAnswer($answer)
    {
        $this->best_answer_id=$answer->id;
        $this->save();
    }
    public function favorites()
    {
        return $this->belongsToMany(User::class,'favorites')->withTimestamps();
    }
    public function isFavorited()
    {
        return $this->favorites()->where('user_id', auth()->id())->count() > 0;
    }
    public function getIsFavoritedAttribute()
    {
        return $this->isFavorited();
    }
    public function getFavoritesCountAttribute()
    {
        return $this->favorites->count();
    }
    public function getExcerptAttribute()
    {
        return $this->excerpt(254);
    }
    public function excerpt($var)
    {
        return Str::limit(strip_tags($this->bodyHtml()),$var );
        # code...
    }
    protected function bodyHtml()
    {
        return \Parsedown::instance()
            ->setBreaksEnabled(true)
            ->text($this->body, 'breaks_enabled');
    }
}

resources/views/shared/_accept.blade.php
    @can('accept',$model)
        <a title="Mark as best" class="{{ $model->status }} mt-2"
            onclick="event.preventDefault(); document.getElementById('accept-{{ $name }}-{{ $model->id }}').submit()"
            >
            <i class="fas fa-check fa-2x"></i>
        </a>
        <form id="accept-{{ $name }}-{{ $model->id }}" action="{{ route($name.'.accept',$model->id)}}" method="POST" style="display: none;">@csrf</form>
    @else
        @if ($model->is_best)
        <a title="This {{ $name }} is marked as best" class="{{ $model->status }} mt-2">
            <i class="fas fa-check fa-2x"></i>
        </a>
        @endif
    @endcan

resources/views/shared/_author.blade.php
<span class="text-mutee mt-2">{{ $label . ' ' . $model->created_date }}</span>
<div class="media mt-2 ml-2 mb-2">
    <a class="pr-2" href="{{$model->user->url }}">
        <img width="{{$model->user->avatarsize }}" height="{{$model->user->avatarsize }}" src="{{$model->user->avatar }}" class="img-fluid" alt="Responsive image">
    </a>
    <div class="media-body">
            <a href="{{$model->user->url }}">
                {{$model->user->name }}</a>
    </div>
</div>

resources/views/shared/_favorite.blade.php
<a title="Mark as favorite" onclick="event.preventDefault(); document.getElementById('favorite-{{ $name }}-{{ $model->id }}').submit()" class="favorite mt-2 {{ Auth::guest() ? 'off' : ($model->is_favorited ? 'favorited' : '' )}}">
<i class="fas fa-star fa-2x "></i>
</a>
<form id="favorite-{{ $name }}-{{ $model->id }}" action="{{route($name.'.favorite',$model->id)}}" method="POST" style="display: none;">
    @csrf
    @if ($model->is_favorited)
    @method('DELETE')
    @endif
</form>
<span class="favorites-count">{{ $model->favorites_count}} </span>

resources/views/shared/_vote.blade.php
@if($model instanceof App\Question)
        @php
            $name = 'question';
        @endphp
@elseif($model instanceof App\Answer)
        @php
            $name = 'answer';
        @endphp
@endif
<div class="d-flex flex-column vote-controls">
    <a title="This $name is useful" onclick="event.preventDefault(); document.getElementById('up-vote-{{ $name }}-{{ $model->id }}').submit()" class="vote-up {{ Auth::guest() ? 'off' : '' }}">
        <i class="fas fa-caret-up fa-3x"></i>
    </a>
    <form id="up-vote-{{ $name }}-{{ $model->id }}" action="{{route($name.'.vote',$model->id)}}" method="POST" style="display: none;">
        @csrf
        @if ($model->is_Voted)
        @method('DELETE')
        @endif
        <input type="hidden" name="vote" value="1">
    </form>
    <span class="rounded-circle votes-count">{{ $model->votes_count }}</span>
    <a title="This {{ $name }} is not useful" onclick="event.preventDefault(); document.getElementById('down-vote-{{ $name }}-{{ $model->id }}').submit()" class="vote-down {{ Auth::guest() ? 'off' : '' }}">
        <i class="fas fa-caret-down fa-3x"></i>
    </a>
    <form id="down-vote-{{ $name }}-{{ $model->id }}" action="{{route($name.'.vote',$model->id)}}" method="POST" style="display: none;">
        @csrf
        @if ($model->is_Voted)
        @method('DELETE')
        @endif
        <input type="hidden" name="vote" value="-1">
    </form>
    @if($model instanceof App\Question)

        <favorite :model="{{ $model }}"></favorite>
    @elseif($model instanceof App\Answer)
        <accept :model="{{ $model }}"></accept>
    @endif
</div>